version: '3.8'

services:
  frontend:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./FrontEnd:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./3TShop
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    # environment:
    #   - SPRING_PROFILES_ACTIVE=dev
    #   - JAVA_OPTS=-Xmx512m -Xms256m
    #   - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/3tshop?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    #   - SPRING_DATASOURCE_USERNAME=root
    #   - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=3tshop
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data: 